# Generated by Django 4.2.5 on 2023-09-25 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0002_register_work'),
    ]

    operations = [
        migrations.CreateModel(
            name='lpg_Customer_Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CUST_ID', models.CharField(max_length=50)),
                ('NAME', models.TextField(max_length=50)),
                ('PHONENUMBER', models.IntegerField()),
                ('SERIAL_NUMBER', models.TextField(max_length=50)),
                ('STARTING_CODE', models.CharField(max_length=50)),
                ('SECRET_KEY', models.CharField(max_length=50)),
                ('DATE', models.DateField()),
                ('GAS_LEAK', models.BooleanField()),
                ('GAS_VALVE', models.BooleanField()),
                ('TAMPER', models.BooleanField()),
                ('DEV_ENABLE', models.BooleanField()),
                ('CYLENDER_TYPE', models.IntegerField()),
                ('PREPAID', models.BooleanField()),
                ('BAT_STATUS', models.IntegerField()),
                ('LOCATION', models.CharField(max_length=50)),
                ('IMEI_NO', models.CharField(max_length=50)),
                ('DEV_STATUS', models.BooleanField()),
                ('DEV_TIME', models.DateField()),
                ('BAL_LPG', models.IntegerField()),
                ('BAL_AMOUNT', models.IntegerField()),
            ],
        ),
    ]
