# Generated by Django 4.2.5 on 2023-09-25 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0003_lpg_customer_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lpg_customer_table',
            name='PHONENUMBER',
            field=models.CharField(max_length=30),
        ),
    ]
