# Generated by Django 4.2.5 on 2023-09-26 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0004_alter_lpg_customer_table_phonenumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='transaction_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isSuccess', models.CharField(max_length=20)),
                ('userName', models.CharField(max_length=30)),
            ],
        ),
    ]
