# Generated by Django 4.2.5 on 2023-09-26 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0005_transaction_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction_details',
            name='phoneNUmber',
            field=models.CharField(default=129817654113, max_length=30),
            preserve_default=False,
        ),
    ]
