# Generated by Django 4.2.4 on 2023-10-16 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0007_admin_alter_lpg_customer_table_bal_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='c2bAmountCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('serialNumber', models.TextField(max_length=50)),
                ('amount', models.FloatField()),
            ],
        ),
    ]
