# Generated by Django 4.2.4 on 2023-10-27 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0008_c2bamountcheck'),
    ]

    operations = [
        migrations.CreateModel(
            name='userHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('SerialNumber', models.TextField(max_length=50)),
                ('Amount', models.FloatField()),
                ('PhoneNumber', models.CharField(max_length=30)),
                ('Date', models.DateField()),
                ('Time', models.TimeField()),
                ('PreviousAmount', models.FloatField()),
                ('NowAddedAmount', models.FloatField()),
                ('PreviousLPG', models.FloatField()),
                ('NewAddedLPG', models.FloatField()),
            ],
        ),
    ]
