# Generated by Django 4.2.4 on 2023-10-30 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0009_userhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='usersLocationInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('SerialNumber', models.TextField(max_length=50)),
                ('PhoneNumber', models.CharField(max_length=30)),
                ('State', models.CharField(max_length=50)),
                ('Country', models.CharField(max_length=50)),
            ],
        ),
    ]
