# Generated by Django 4.2.4 on 2023-11-27 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0010_userslocationinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='lpg_customer_table',
            name='USER_EMAIL',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
