# Generated by Django 4.2.6 on 2023-12-07 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0011_lpg_customer_table_user_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lpg_customer_table',
            old_name='USER_EMAIL',
            new_name='USER_EMAILS',
        ),
    ]
