# Generated by Django 4.2.6 on 2023-12-07 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0012_rename_user_email_lpg_customer_table_user_emails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lpg_customer_table',
            old_name='USER_EMAILS',
            new_name='USER_EMAIL',
        ),
    ]
