# Generated by Django 4.2.4 on 2023-12-13 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0013_rename_user_emails_lpg_customer_table_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='usageHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SerialNumber', models.TextField(max_length=50)),
                ('Name', models.CharField(max_length=50)),
                ('DATE', models.DateField()),
                ('Time', models.TimeField()),
                ('BAL_LPG', models.FloatField()),
                ('BAL_AMOUNT', models.FloatField()),
                ('Extra1', models.CharField(max_length=50)),
                ('Extra2', models.CharField(max_length=50)),
            ],
        ),
        
    ]
