# Generated by Django 4.2.4 on 2023-12-13 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0014_usagehistory_userlowbalancecheck_and_more'),
    ]

    operations = [
       
       
        migrations.RenameField(
            model_name='usagehistory',
            old_name='Extra1',
            new_name='Battery',
        ),
        migrations.RenameField(
            model_name='usagehistory',
            old_name='Extra2',
            new_name='Others',
        ),
    ]
