# Generated by Django 4.2.4 on 2023-12-20 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0015_userlowbalancecheck_and_more'),
    ]

    operations = [
        
        migrations.RenameField(
            model_name='c2bamountcheck',
            old_name='serialNumber',
            new_name='PhoneNumber',
        ),
        
    ]
