# Generated by Django 4.2.4 on 2024-01-08 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0016_userlowbalancecheck_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GasPrices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_name', models.CharField(max_length=50)),
                ('gas_units', models.IntegerField()),
                ('price', models.FloatField()),
            ],
        ),
    ]
