# Generated by Django 4.2.4 on 2024-01-08 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0017_gasprices_userlowbalancecheck_and_more'),
    ]

    operations = [
        
        migrations.AddField(
            model_name='gasprices',
            name='date',
            field=models.DateField(default='2023-10-24'),
        ),
        migrations.AddField(
            model_name='gasprices',
            name='time',
            field=models.TimeField(default='09:37:07.0'),
        ),
    ]
