# Generated by Django 5.0.1 on 2024-01-16 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0018_userlowbalancecheck_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='customerIssues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('problem_one', models.TextField()),
                ('problem_two', models.TextField()),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
        ),
        
    ]
