# Generated by Django 5.0.1 on 2024-01-16 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0019_customerissues_userlowbalancecheck_and_more'),
    ]

    operations = [
       
        
       
        migrations.AddField(
            model_name='customerissues',
            name='phonenumber',
            field=models.IntegerField(),
        ),
    ]
