# Generated by Django 4.2.4 on 2024-01-22 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0020_userlowbalancecheck_and_more'),
    ]

    operations = [
        
        migrations.AddField(
            model_name='customerissues',
            name='status',
            field=models.BooleanField(default='False'),
        ),
        migrations.AddField(
            model_name='customerissues',
            name='token',
            field=models.TextField(default='EVM001'),
        ),
        
    ]
