# Generated by Django 4.2.4 on 2024-01-22 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0021_userlowbalancecheck_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='solvedIssues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('problem_one', models.TextField()),
                ('problem_two', models.TextField()),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('phonenumber', models.IntegerField(default='+919703323212')),
                ('email', models.EmailField(default='enerziff@gmail.com', max_length=254)),
                ('token', models.TextField(default='EVM001')),
            ],
        ),
        
        
    ]
