# Generated by Django 4.2.4 on 2024-03-19 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0022_solvedissues_userlowbalancecheck_and_more'),
    ]

    operations = [
        
       
        migrations.AddField(
            model_name='userhistory',
            name='Location',
            field=models.CharField(default=2313, max_length=50),
            preserve_default=False,
        ),
       
    ]
