# Generated by Django 4.2.4 on 2024-03-20 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0023_userlowbalancecheck_and_more'),
    ]

    operations = [
       
        migrations.AlterField(
            model_name='lpg_customer_table',
            name='DEV_TIME',
            field=models.DateTimeField(),
        ),
    ]
