# Generated by Django 4.2.4 on 2024-03-21 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0024_userlowbalancecheck_and_more'),
    ]

    operations = [
       
       
       
        migrations.AddField(
            model_name='lpg_customer_table',
            name='AREA_LEAD',
            field=models.CharField(default=12, max_length=50),
            preserve_default=False,
        ),
       
    ]
