# Generated by Django 4.2.4 on 2024-03-21 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0025_lpg_status_infos_userlowbalancecheck_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area_Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('password', models.TextField(max_length=20)),
                ('email', models.CharField(max_length=30)),
            ],
        ),
       
    ]
