# Generated by Django 4.2.4 on 2024-03-21 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0026_area_lead_lpg_status_infos_userlowbalancecheck_and_more'),
    ]

    operations = [
        
        migrations.AddField(
            model_name='userhistory',
            name='Area_Lead',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
       
    ]
