# Generated by Django 4.2.4 on 2024-03-25 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0027_lpg_status_infos_userlowbalancecheck_and_more'),
    ]

    operations = [
       
        migrations.AddField(
            model_name='customerissues',
            name='Location',
            field=models.CharField(default=23, max_length=50),
            preserve_default=False,
        ),
      
    ]
