# Generated by Django 4.2.4 on 2024-03-25 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0028_lpg_status_infos_userlowbalancecheck_and_more'),
    ]

    operations = [
       
        
        migrations.RenameField(
            model_name='customerissues',
            old_name='Location',
            new_name='Area_Lead',
        ),
       
       
        migrations.AddField(
            model_name='solvedissues',
            name='Area_Lead',
            field=models.CharField(default=231, max_length=50),
            preserve_default=False,
        ),
      
    ]
