from django.urls import path
from . import views

urlpatterns = [
     path('', views.home, name='home'),
  
    # path('datapicking/', views.datapicking, name='datapicking'),
    path('reg/', views.reg, name='reg'),
    path('login/', views.login, name='login'),
    path('addDetails/<str:userName>',views.addDetails,name = 'addDetails'),
    path('editDetails/', views.editDetails, name='editDetails'),
    path('editall/<str:userName>', views.editall, name='editall'),
    path('update/<str:userName>', views.update, name='update'),
    path('amountinput/<str:userName>', views.amountinput, name='amountinput'),
    path('payment/<str:userName>', views.payment, name='payment'),
    path('deleteUser/', views.deleteUser, name='deleteUser'),
    path('relogin/<str:userName>', views.relogin, name='relogin'),
    path('adminLogin/', views.adminLogin, name='adminLogin'),
    path('checkAdminLogin/', views.checkAdminLogin, name='checkAdminLogin'),
    path('adminEdit/<str:NAME>/<str:user_type>', views.adminEdit, name='adminEdit'),
    path('selectEdit/<str:NAME>/<str:user_type>/<str:name>', views.selectEdit, name='selectEdit'),
    path('adminupdate/<str:userName>/<str:NAME>/<str:user_type>', views.adminupdate, name='adminupdate'),
    path('adminHome/<str:NAME>/<str:user_type>', views.adminHome, name='adminHome'),
    path('UserLocation/<str:location>/<str:NAME>/<str:user_type>', views.UserLocation, name='UserLocation'),
    path(' c2bPaymentCheck/', views. c2bPaymentCheck, name=' c2bPaymentCheck'),
    path('historydata/<str:userName>', views.historydata, name='historydata'), 
    path('customerHelp/', views.customerHelp, name='customerHelp'),
    path('usedHistory/<str:userName>', views.usedHistory, name='usedHistory'),
    path('usedHistoryAdmin1/<str:UserName>/<str:NAME>/<str:user_type>', views.usedHistoryAdmin1, name='usedHistoryAdmin1'),
    path('usedHistoryAdmin/', views.usedHistoryAdmin, name='usedHistoryAdmin'),
    path('MeterStatus/<str:PhoneNumber>/<str:NAME>/<str:user_type>', views.MeterStatus, name='MeterStatus'),
    path('usedHistoryMailSend/<str:userName>', views.usedHistoryMailSend, name='usedHistoryMailSend'),
    path('AdminHistoryMailSend/', views.AdminHistoryMailSend, name='AdminHistoryMailSend'),
    path('setPrices/<str:NAME>/<str:user_type>', views.setPrices, name='setPrices'),
    path('raiseComplaint/<str:userName>', views.raiseComplaint, name='raiseComplaint'),
    path('issuesSolving/', views.issuesSolving, name='issuesSolving'),
    path('chatBot/', views.chatBot, name='chatBot'),
    path('forgotPassword/', views.forgotPassword, name='forgotPassword'),
    path('validatePassword/', views.validatePassword, name='validatePassword'),
     path('userForgotPassword/', views.userForgotPassword, name='userForgotPassword'),
    path('userValidatePassword/', views.userValidatePassword, name='userValidatePassword'),
    path('userValidatePassword/', views.userValidatePassword, name='userValidatePassword'),
    path('userComplainHistory/<str:userName>', views.userComplainHistory, name='userComplainHistory'),
    path('adminComplaintHistory/<str:NAME>/<str:user_type>', views.adminComplaintHistory, name='adminComplaintHistory'),
    path('getAdmin_message/', views.getAdmin_message, name='getAdmin_message'),
    path('checkPaymentStatus/<str:userName>/<int:number>/<str:phonenumber>', views.checkPaymentStatus, name='checkPaymentStatus'),
    path('DisplayRecharge_Amount/<str:request_type>/<str:NAME>/<str:user_type>', views.DisplayRecharge_Amount, name='DisplayRecharge_Amount'),
    path('download_csv/<str:userName>', views.download_csv, name='download_csv'),
    path('Download_Per_Day/<str:input1>/<str:request_type>', views.Download_Per_Day, name='Download_Per_Day'),
    path('Download_Individual/<str:input1>', views.Download_Individual, name='Download_Individual'),
    path('Download_Location/<str:input1>', views.Download_Location, name='Download_Location'),
    path(' Download_Per_Month/<str:input1>/<str:input2>', views. Download_Per_Month, name=' Download_Per_Month'),
    path(' Download_Between_Dates/<str:input1>/<str:input2>', views. Download_Between_Dates, name=' Download_Between_Dates'),
    path(' Download_Month_Individual/<str:input1>/<str:input2>/<str:input3>', views. Download_Month_Individual, name=' Download_Month_Individual'),
    path(' Download_Location_Month/<str:input1>/<str:input2>/<str:input3>', views. Download_Location_Month, name=' Download_Location_Month'),
    path('areaLeadLogin/', views.areaLeadLogin, name='areaLeadLogin'),
    path('Customer_Reports/<str:NAME>/<str:user_type>', views.Customer_Reports, name='Customer_Reports'),
    path('Configuration/<str:NAME>/<str:user_type>/<str:request_type>', views.Configuration, name='Configuration'),
    path('history_download_csv/<str:userName>/<str:start_date>/<str:end_date>', views.history_download_csv, name='historyDownloadCSV'),
    path('history_data_pdf/<str:userName>/<str:start_date>/<str:end_date>', views.history_data_pdf, name='history_data_pdf'),
    
]
